name: "ms_lessons"
services:
  user:
    build:
      context: .
      dockerfile: user/Dockerfile
    ports:
      - "8081:8080"
  friend:
    build:
      context: .
      dockerfile: friend/Dockerfile
    ports:
      - "8082:8080"
  chat:
    build:
      context: .
      dockerfile: chat/Dockerfile
    ports:
      - "8083:8080"
  auth:
    build:
      context: .
      dockerfile: auth/Dockerfile
    ports:
      - "8084:8080"